spring:
  application:
    name: hc-auth-api

  jackson:
    serialization:
      indent_output: true

logging:
  level:
    root: INFO
    com.hedgecourt: DEBUG
    org.springframework.web: INFO
    org.springframework.web.filter: INFO
    org.springframework.web.servlet.DispatcherServlet: INFO

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:mem:hc_db
    driverClassName: org.h2.Driver
    username: hc_user
    password: devpass123
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

hc:
  env: dev

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:hc_db
    driverClassName: org.h2.Driver
    username: hc_user
    password: testpass123
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

hc:
  env: test

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:h2:mem:hc_db
    driverClassName: org.h2.Driver
    username: REDACTED
    password: REDACTED
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

hc:
  env: prod
