spring:
  application:
    name: hc-auth-api

  jackson:
    serialization:
      indent_output: true

logging:
  level:
    root: INFO
    com.hedgecourt: DEBUG
    org.springframework.web: INFO
    org.springframework.web.filter: INFO
    org.springframework.web.servlet.DispatcherServlet: INFO

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

hc:
  jwt:
    # enable token creation and signing
    auth-enabled: true
    # 1 day = 86400000
    expiry-millis: 86400000
    # if generate-keys is true, override the key files and generate throw-away key pair
    generate-keys: false
    # if generate-keys is false, load keys from resource
    public-key-resource: classpath:jwt/public.pem
    private-key-resource: classpath:jwt/private.pem

  auth:
    init:
      password: REDACTED

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:mem:hc_db
    driverClassName: org.h2.Driver
    username: hc_user
    password: devpass123
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

hc:
  env: dev

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:hc_db
    driverClassName: org.h2.Driver
    username: hc_user
    password: testpass123
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

hc:
  env: test

  jwt:
    # in test profile, generate throw-away keys
    generate-keys: true

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:h2:mem:hc_db
    driverClassName: org.h2.Driver
    username: REDACTED
    password: REDACTED
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

hc:
  env: prod
