spring:
  application:
    name: hc-auth-api
  security:
    enabled: false

  jackson:
    serialization:
      indent_output: true

logging:
  level:
    root: INFO
    com.hedgecourt: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.filter: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG

---
spring:
  config:
    activate:
      on-profile: dev

hc:
  env: dev

---
spring:
  config:
    activate:
      on-profile: test

hc:
  env: test

---
spring:
  config:
    activate:
      on-profile: prod

hc:
  env: prod
