name: Publish Docker Image

on:
  workflow_run:
    workflows: [ "Verify Build" ]
    types:
      - completed

env:
  REGISTRY: ghcr.io
  #IMAGE_NAME: ${{ github.repository }}
  # the github.repository is hc-spring-monorepo
  IMAGE_NAME: hc-auth-api

jobs:
  build-docker:
    if: ${{ success() && github.ref == 'refs/heads/main' }}

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./hc-auth-api

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Inspect working directory
        run: |
          echo "Working directory..."
          pwd
          ls -lart

      - name: Inspect hc-auth-api
        run: ls -lart hc-auth-api

      - name: Inspect hc-spring-lib
        run: ls -lart hc-spring-lib

      - name: Login to GitHub Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image to GitHub Container registry
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
