name: Verify Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  maven:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Report non-main branch
        if: github.ref != 'refs/heads/main'
        run: echo 'Not on [main] branch - [${{ github.ref }}]'

      - name: Report main branch
        if: github.ref == 'refs/heads/main'
        run: echo 'On [main] branch - [${{ github.ref }}]'

      - name: Maven verify
        run: mvn --batch-mode --update-snapshots verify

      - name: Inspect working directory
        run: |
          echo "Working directory..."
          pwd
          ls -lart

      - name: List target dirs
        run: find . -type d -name "target"

      - name: Inspect hc-spring-lib/target
        run: ls -lart hc-spring-lib/target

      - name: Inspect hc-auth-api/target
        run: ls -lart hc-auth-api/target

      - name: Upload maven target
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: maven-target
          path: hc-auth-api/target/

      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      #- name: Update dependency graph
      #  uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

  docker:
    if: ${{ github.ref == 'refs/heads/main' }}

    runs-on: ubuntu-latest
    needs: maven
    defaults:
      run:
        working-directory: hc-auth-api

    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4

      - name: Download maven target
        uses: actions/download-artifact@v4
        with:
          name: maven-target
          path: hc-auth-api/target/

      - name: Inspect working directory
        run: |
          echo "Working directory..."
          pwd
          ls -lart

      - name: List target dirs
        run: find . -type d -name "target"

      - name: Inspect target
        run: ls -lart target
